# Generated by Django 4.2.27 on 2025-12-04 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0011_channel_stream_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='channel_logo_url',
            field=models.URLField(blank=True, max_length=1200, null=True),
        ),
    ]
