# Generated by Django 4.2.27 on 2025-12-05 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0012_alter_channel_channel_logo_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramGuide",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=256)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name="EPGChannels",
        ),
        migrations.DeleteModel(
            name="Programmes",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="channel_logo",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="channel_protected",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="epg_id",
        ),
        migrations.RemoveField(
            model_name="channel",
            name="stream_active",
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_group",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_logo_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_name",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="channel",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="tvg_id",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name="programguide",
            name="channel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="programguides",
                to="stream.channel",
            ),
        ),
    ]
