# Generated by Django 4.2.27 on 2025-12-05 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0013_programguide_delete_epgchannels_delete_programmes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_group",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="channel",
            name="channel_name",
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name="channel",
            name="tvg_id",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="programguide",
            name="title",
            field=models.CharField(max_length=512),
        ),
    ]
