# Generated by Django 4.2.27 on 2025-12-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stream", "0014_alter_channel_channel_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="channel_logo_url",
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
